
from prometheus_client import Counter, Gauge, Histogram # Added Histogram for potential future use

# --- Genetic Algorithm Metrics ---

# Gauges: Values that can go up and down
GA_CURRENT_GENERATION = Gauge(
    'prompthelix_ga_current_generation_number',
    'Current generation number of the Genetic Algorithm'
)

GA_BEST_FITNESS = Gauge(
    'prompthelix_ga_best_fitness_score',
    'Best fitness score in the current GA generation'
)

GA_AVG_FITNESS = Gauge(
    'prompthelix_ga_average_fitness_score',
    'Average fitness score in the current GA generation'
)

GA_MEDIAN_FITNESS = Gauge(
    'prompthelix_ga_median_fitness_score',
    'Median fitness score in the current GA generation'
)

GA_MIN_FITNESS = Gauge(
    'prompthelix_ga_min_fitness_score',
    'Minimum fitness score in the current GA generation'
)

GA_STD_DEV_FITNESS = Gauge(
    'prompthelix_ga_std_dev_fitness_score',
    'Standard deviation of fitness scores in the current GA generation'
)

GA_POPULATION_SIZE = Gauge(
    'prompthelix_ga_population_size',
    'Current size of the GA population'
)

GA_RUNNING_STATUS = Gauge(
    'prompthelix_ga_running_status',
    'Status of the GA run (1 for running/active, 0 for idle/stopped/completed/error)'
    # Could also use an Enum with states if preferred and supported well by dashboards
)


# Counters: Values that only go up
GA_EVALUATIONS_TOTAL = Counter(
    'prompthelix_ga_evaluations_total',
    'Total number of chromosome fitness evaluations performed'
)

GA_SUCCESSFUL_EVALUATIONS_TOTAL = Counter(
    'prompthelix_ga_successful_evaluations_total',
    'Total number of successful chromosome fitness evaluations'
)

GA_FAILED_EVALUATIONS_TOTAL = Counter(
    'prompthelix_ga_failed_evaluations_total',
    'Total number of failed chromosome fitness evaluations (e.g. timeout, LLM error)'
)

GA_MUTATIONS_TOTAL = Counter(
    'prompthelix_ga_mutations_total',
    'Total number of mutation operations performed on chromosomes'
)

GA_CROSSOVERS_TOTAL = Counter(
    'prompthelix_ga_crossovers_total',
    'Total number of crossover operations performed between chromosomes'
)

GA_ELITE_INDIVIDUALS_TOTAL = Counter(
    'prompthelix_ga_elite_individuals_carried_over_total',
    'Total number of elite individuals carried over to the next generation'
)

# Example Histogram (Optional - can be added if detailed timing/score distributions are needed)
# GA_FITNESS_SCORE_DISTRIBUTION = Histogram(
#     'prompthelix_ga_fitness_score_distribution',
#     'Distribution of fitness scores in GA generations',
#     buckets=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0] # Example buckets
# )

# TODO: Add more metrics as needed, e.g., specific mutation strategy counts,
# LLM call latencies (if instrumented), error counts by type, etc.

# --- Application Level Metrics (Example) ---
# HTTP_REQUESTS_TOTAL = Counter(
# 'prompthelix_http_requests_total',
# 'Total number of HTTP requests made to the application',
# ['method', 'endpoint', 'status_code']
# )

# --- Agent Specific Metrics (Example - could be in agent modules) ---
# AGENT_MESSAGES_PROCESSED_TOTAL = Counter(
# 'prompthelix_agent_messages_processed_total',
# 'Total messages processed by an agent',
# ['agent_id', 'message_type']
# )

# --- LLM Call Metrics ---
LLM_CALL_LATENCY_SECONDS = Histogram(
    'prompthelix_llm_call_latency_seconds',
    'Latency of LLM API calls in seconds',
    ['llm_provider', 'llm_model']
)

LLM_INPUT_TOKENS_TOTAL = Counter(
    'prompthelix_llm_input_tokens_total',
    'Total number of input tokens processed by LLMs',
    ['llm_provider', 'llm_model']
)

LLM_OUTPUT_TOKENS_TOTAL = Counter(
    'prompthelix_llm_output_tokens_total',
    'Total number of output tokens generated by LLMs',
    ['llm_provider', 'llm_model']
)

LLM_CALLS_TOTAL = Counter(
    'prompthelix_llm_calls_total',
    'Total number of LLM API calls',
    ['llm_provider', 'llm_model', 'status'] # status can be 'success' or 'error'
)


def initialize_ga_metrics():
    """
    Initializes GA-specific metrics to a starting state (e.g., 0 or specific values).
    Useful if the application might restart and you want to ensure gauges are reset
    or set to a known state if they are not already registered (Prometheus client handles
    reregistration gracefully but not necessarily resetting values across restarts unless designed so).
    For most counters, this is not strictly needed as they start at 0.
    For gauges, setting them to 0 or a default "not running" state can be useful.
    """
    GA_CURRENT_GENERATION.set(0)
    GA_BEST_FITNESS.set(0)
    GA_AVG_FITNESS.set(0)
    GA_MEDIAN_FITNESS.set(0)
    GA_MIN_FITNESS.set(0)
    GA_STD_DEV_FITNESS.set(0)
    GA_POPULATION_SIZE.set(0)
    GA_RUNNING_STATUS.set(0) # 0 = not running

    # Counters effectively start at 0, but explicit calls don't hurt if one wanted to ensure.
    # However, .inc() is the typical usage. For a true reset (if ever needed, not typical for counters):
    # prometheus_client.REGISTRY.unregister(GA_EVALUATIONS_TOTAL)
    # GA_EVALUATIONS_TOTAL = Counter(...) and then re-register or let it auto-register.
    # This is complex. Usually, counters just accumulate.

# Note: Calling initialize_ga_metrics() could be done at application startup,
# particularly before a GA run might begin if there's a clear "start" point.
# If the GA runs continuously or on demand, these will be updated as it runs.
# For now, we'll rely on them being set during the GA lifecycle.
# If the app restarts, gauges will reset to 0 by default if not set.
# Counters will effectively restart from 0 for the new process.
"""old

from fastapi import APIRouter, Response
from prometheus_client import Gauge, generate_latest, CONTENT_TYPE_LATEST, counter

from .wandb_logger import log_metrics

# Gauges for key GA metrics
GA_GENERATION = Gauge(
    "prompthelix_ga_generation",
    "Current generation of the running genetic algorithm",
)
GA_BEST_FITNESS = Gauge(
    "prompthelix_ga_best_fitness",
    "Best fitness score of the current generation",
)

router = APIRouter()


@router.get("/metrics")
def metrics() -> Response:
#   
    data = generate_latest()
    return Response(content=data, media_type=CONTENT_TYPE_LATEST)


def update_ga_metrics(generation: int, best_fitness: float | None) -> None:
   
    GA_GENERATION.set(generation)
    if best_fitness is not None:
        GA_BEST_FITNESS.set(best_fitness)
    log_metrics(
        {
            "prompthelix_ga_generation": generation,
            "prompthelix_ga_best_fitness": best_fitness,
        }
    )

from prometheus_client import Gauge, Counter

# GA metrics

ga_current_generation = Gauge("ga_current_generation", "Current GA generation")

ga_best_fitness = Gauge("ga_best_fitness", "Best fitness score this generation")

ga_population_size = Gauge("ga_population_size", "Population size after generation")

ga_evaluations_total = Counter("ga_evaluations_total", "Total chromosome evaluations")

def record_generation(generation: int, population_size: int, best_fitness: float, evaluated_count: int):

    ga_current_generation.set(generation)
    ga_population_size.set(population_size)
    ga_best_fitness.set(best_fitness)
    ga_evaluations_total.inc(evaluated_count)

"""
